### PR TITLE
Added the code for repeating the words on request

### PR DESCRIPTION
**Pull request by AADIdevoloper**
Read README.md for all details of all the changes I have done.

### CODE REVIEW

**Comment by AADIdevoloper** [comment]
@Svanik-Jain , please squash annd merge this branch, because there have been very minor changes earlier in the code...

**Comment by Svanik-Jain** [comment]
Small request
Next time don't put what you have done in the readme file.
You can send it here. That file is for showing what your program does.

**Comment by Svanik-Jain** [comment]
## Additions I have made:

I have added the feature to read some part of the text if someone misses out, then read on further if some more is left out
The code first finds the lines that the person is refering to, then reads comlete line, plus a line further.
If the person has left out more, it asks if more is to be read.
It also asks several times so that many parts can be read out again.

Also, in the start I also added the feature to slow down the speed (because this is a text dictator.)

## One last step to project completion!!!


#### All that is left for this to put the module that converts speech to text.
It will be used when:
  1. which page number is to be dictated                                      --------> go to line 13 in code
  2. what part is to be read again (variable name is "reread")                --------> go to line 39 in code
  3. whether the part read again is to be continued (variable name is "readon")-------> go to line 47 in code

All we have to do is to replace the input() function when speech to text answer.
Rest all is done!

*In case you haven't understood the code, I will properly explain everything in our next meeting*

**Comment by Svanik-Jain** [comment]
I have added some additional functionality:

1) The lines are read one by one.(I have put the text reading function in a for loop.
2) I have added the signal module to stop the code with ctrl+c.
3) I have also added a dummy template in the readme.md file.

**Pull request merged**
